"""Paper E flight-class table from committed evidence.

tables/tab_flightclass.tex holds measured Raspberry-Pi-5 (real hardware) budgets for the
controller+shield hot loop and the int4 commander, plus the live-shield overhead from the
closed-loop integration. Sources: evidence/sandbox/pi_a53_gate.json,
evidence/program/closed_loop_integration.json. Run from repo root:
python -m paper.hil.tables
"""

from __future__ import annotations

import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PI = json.loads((ROOT / "evidence/sandbox/pi_a53_gate.json").read_text())
CL = json.loads((ROOT / "evidence/program/closed_loop_integration.json").read_text())
HF_PATH = ROOT / "evidence/program/hifi_fault_campaign.json"
HF = json.loads(HF_PATH.read_text()) if HF_PATH.exists() else None
TBL = Path(__file__).resolve().parent / "tables"
TBL.mkdir(exist_ok=True)


def _pct(x: float) -> str:
    return f"{100 * x:.1f}"


def _ci(ci: list) -> str:
    return f"[{100 * ci[0]:.1f}, {100 * ci[1]:.1f}]"


def hifi_table() -> None:
    """tab_hifi.tex: the high-fidelity closed-loop fault campaign (air-bearing substitute)."""
    if HF is None:
        print("hifi_fault_campaign.json absent; skipping tab_hifi.tex")
        return
    h = HF["headline"]
    nm = HF["nonideality_model"]
    res = HF["results"]
    rma, ideal, pd = (
        h["rma_hifi_designed_pooled"],
        h["rma_ideal_designed_pooled"],
        h["pd_hifi_designed_pooled"],
    )
    gb = res["rma_hifi_beyond_scope"]["gain_bias"]
    tl = res["rma_hifi_beyond_scope"]["total_loss"]
    mom = res["rma_hifi_stored_momentum_gain"]
    shld = res["rma_hifi_designed"]["gain"]
    nf = HF["n_faults_per_class"]
    ns = HF["n_seeds"]
    di, dh = _pct(ideal["autonomous_recovery_rate"]), _pct(rma["autonomous_recovery_rate"])
    dci, dpd = _ci(rma["autonomous_recovery_wilson95"]), _pct(pd["autonomous_recovery_rate"])
    gbr, gbe = _pct(gb["autonomous_recovery_rate"]), _pct(gb["escalation_rate"])
    tlr, tle = _pct(tl["autonomous_recovery_rate"]), _pct(tl["escalation_rate"])
    mor, moe = _pct(mom["autonomous_recovery_rate"]), _pct(mom["escalation_rate"])
    lines = [
        "% AUTO-GENERATED by paper/hil/tables.py (hifi_fault_campaign evidence)",
        "\\begin{table}[h]\\centering\\small",
        "\\caption{High-fidelity closed-loop fault campaign, the computational analogue of a "
        "physical air-bearing run. The deployed stack (latched RMA student, the real Kind-2 "
        f"LTLMonitor, and Basilisk dynamics) is exercised in reaction-wheel mode with friction, "
        f"under star-tracker noise ({nm['att_noise_deg']:.2f}$^\\circ$, 1$\\sigma$) and bias, gyro "
        f"noise ({nm['rate_noise_deg_s']:.2f}$^\\circ$/s) and bias, {nm['cmd_bits']}-bit actuator "
        f"resolution, and a {100 * nm['deadband']:.0f}\\% motor deadband. Each cell is "
        f"$n={nf}\\times{ns}$ held-out (test-split) faults. Recovery is the live shield certifying "
        "autonomy over the final dwell; rates carry Wilson 95\\% intervals.}",
        "\\label{tab:hifi}",
        "\\begin{tabular}{lcccc}",
        "\\toprule",
        "Fault regime & RMA ideal & RMA high-fidelity & Fault-unaware PD & Shield action \\\\",
        "\\midrule",
        f"Designed scope (gain, sign), $n={rma['n_trials']}$ & {di}\\% "
        f"& {dh}\\% {dci} & {dpd}\\% & certifies autonomy \\\\",
        "\\midrule",
        "\\multicolumn{5}{l}{\\emph{Beyond the estimator's scope (gain, sign, "
        "inertia, not bias), the shield escalates}} \\\\",
        f"Additive bias, $n={gb['n_trials']}$ & n/a & {gbr}\\% recover "
        f"& {dpd}\\% & escalates {gbe}\\% \\\\",
        f"Dead axis, $n={tl['n_trials']}$ & n/a & {tlr}\\% recover "
        f"& n/a & escalates {tle}\\% \\\\",
        f"Stored momentum (gain), $n={mom['n_trials']}$ & n/a & {mor}\\% recover "
        f"& n/a & escalates {moe}\\% \\\\",
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
        "",
    ]
    (TBL / "tab_hifi.tex").write_text("\n".join(lines), encoding="utf-8")
    print(
        f"wrote {TBL / 'tab_hifi.tex'} | shield in hi-fi loop: "
        f"{shld['measured_shield_latency_us']['mean']:.1f}us "
        f"({shld['shield_overhead_pct_at_10hz']:.2f}% @10Hz)"
    )


def main() -> None:
    cs = PI["controller_shield"]
    cm = PI["commander_int4_gguf"]
    pw = PI["power"]
    rma = CL["by_controller"]["rma_latched"]
    rss_mb = math.floor(cm["peak_rss_mb"] + 0.5)  # round-half-up to match prose/abstract (437)
    lines = [
        "% AUTO-GENERATED by paper/hil/tables.py (pi_a53_gate + closed_loop_integration evidence)",
        "\\begin{table}[h]\\centering\\small",
        "\\caption{Flight-class measurements on a \\emph{real} Raspberry~Pi~5 (quad Cortex-A76), "
        "the A53/A72-class stand-in the proposal called for, closing the ``QEMU is not a flight "
        "CPU'' gap on the silicon class that flies. The controller$+$shield hot loop runs "
        "cycle-accurately at the 10\\,Hz real-time tier with thousands-fold timing margin, so a "
        "slower hardened flight part stays well within budget; the commander runs at mission-event "
        "cadence (its tok/s sets goal-generation latency, not the control budget). The live-shield "
        "overhead is measured \\emph{in} the closed-loop Basilisk integration on honest pointing "
        "state, not in a stand-alone microbenchmark.}",
        "\\label{tab:flightclass}",
        "\\begin{tabular}{lll}",
        "\\toprule",
        "Quantity & Measured & Budget / note \\\\",
        "\\midrule",
        f"Controller$+$shield cycle & {cs['ms_per_cycle']:.3f}\\,ms "
        f"(${cs['ns_per_cycle'] / 1000:.1f}\\,\\mu$s) & "
        f"$\\approx${100 / cs['ms_per_cycle']:.0f}$\\times$ under the 100\\,ms 10\\,Hz gate \\\\",
        f"Controller$+$shield resident set & {cs['peak_rss_mb']:.1f}\\,MB & hot loop \\\\",
        f"Live-shield overhead (closed loop) & {rma['shield_overhead_pct_at_10hz']:.2f}\\% "
        f"(${rma['measured_latency_us']['shield_mean']:.1f}\\,\\mu$s) & RMA kept "
        f"{rma['autonomous_recovery_rate'] * 100:.0f}\\% autonomous \\\\",
        f"Commander (int4 GGUF) throughput & {cm['tokens_per_second']:.1f}\\,tok/s "
        f"({cm['goal_gen_latency_s']:.2f}\\,s/goal) & mission-event cadence \\\\",
        f"Commander resident set & {rss_mb:d}\\,MB & fits the 512\\,MB cap \\\\",
        f"Board power & {pw['power_w_idle']:.1f}\\,W idle / {pw['power_w_peak']:.1f}\\,W peak & "
        f"$\\approx${pw['power_w_core_attributable']:.1f}\\,W core-attributable \\\\",
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
        "",
    ]
    (TBL / "tab_flightclass.tex").write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {TBL / 'tab_flightclass.tex'}")
    hifi_table()


if __name__ == "__main__":
    main()
